# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(859, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, -2, 845, 648))
        self.tabWidget.setMinimumSize(QtCore.QSize(641, 421))
        self.tabWidget.setMaximumSize(QtCore.QSize(845, 648))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(690, 480, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.treeWidget = QtWidgets.QTreeView(self.tab)
        self.treeWidget.setGeometry(QtCore.QRect(30, 50, 271, 471))
        self.treeWidget.setTabKeyNavigation(False)
        self.treeWidget.setProperty("showDropIndicator", True)
        self.treeWidget.setDragEnabled(True)
        self.treeWidget.setDragDropOverwriteMode(False)
        self.treeWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.treeWidget.setDefaultDropAction(QtCore.Qt.LinkAction)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treeWidget.setAutoExpandDelay(0)
        self.treeWidget.setIndentation(20)
        self.treeWidget.setUniformRowHeights(False)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.header().setVisible(False)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(100)
        self.treeWidget.header().setHighlightSections(True)
        self.treeWidget.header().setMinimumSectionSize(100)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.treeWidget.header().setStretchLastSection(True)
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(420, 50, 221, 471))
        self.listWidget.setAutoScroll(True)
        self.listWidget.setProperty("showDropIndicator", True)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropOverwriteMode(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setUniformItemSizes(False)
        self.listWidget.setObjectName("listWidget")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QtCore.QRect(680, 50, 111, 31))
        self.checkBox.setObjectName("checkBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(340, 50, 42, 471))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(422, 20, 221, 20))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(32, 20, 221, 20))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_6.setEnabled(False)
        self.checkBox_6.setGeometry(QtCore.QRect(680, 50, 111, 31))
        self.checkBox_6.setObjectName("checkBox_6")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_22.setGeometry(QtCore.QRect(690, 480, 91, 41))
        self.pushButton_22.setObjectName("pushButton_22")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(422, 20, 221, 20))
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(340, 50, 42, 471))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_9.setEnabled(True)
        self.pushButton_9.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_11 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_11.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_3.addWidget(self.pushButton_11)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(32, 20, 221, 20))
        self.label_7.setObjectName("label_7")
        self.treeWidget_6 = QtWidgets.QTreeWidget(self.tab_2)
        self.treeWidget_6.setGeometry(QtCore.QRect(30, 50, 271, 471))
        self.treeWidget_6.setDragEnabled(True)
        self.treeWidget_6.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.treeWidget_6.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.treeWidget_6.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeWidget_6.setAutoExpandDelay(0)
        self.treeWidget_6.setIndentation(5)
        self.treeWidget_6.setUniformRowHeights(False)
        self.treeWidget_6.setColumnCount(1)
        self.treeWidget_6.setObjectName("treeWidget_6")
        self.treeWidget_6.header().setVisible(False)
        self.treeWidget_6.header().setCascadingSectionResizes(False)
        self.treeWidget_6.header().setDefaultSectionSize(100)
        self.treeWidget_6.header().setHighlightSections(True)
        self.treeWidget_6.header().setMinimumSectionSize(100)
        self.treeWidget_6.header().setSortIndicatorShown(False)
        self.treeWidget_6.header().setStretchLastSection(True)
        self.listWidget_2 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_2.setGeometry(QtCore.QRect(420, 50, 221, 471))
        self.listWidget_2.setAutoScroll(True)
        self.listWidget_2.setDragEnabled(True)
        self.listWidget_2.setDragDropOverwriteMode(True)
        self.listWidget_2.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.listWidget_2.setDefaultDropAction(QtCore.Qt.TargetMoveAction)
        self.listWidget_2.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listWidget_2.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget_2.setUniformItemSizes(False)
        self.listWidget_2.setObjectName("listWidget_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setGeometry(QtCore.QRect(680, 50, 111, 31))
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_13.setGeometry(QtCore.QRect(690, 480, 91, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(422, 20, 221, 20))
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(340, 50, 42, 471))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_12 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_12.setEnabled(True)
        self.pushButton_12.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_4.addWidget(self.pushButton_12)
        self.pushButton_14 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_14.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_4.addWidget(self.pushButton_14)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(32, 20, 221, 20))
        self.label_5.setObjectName("label_5")
        self.treeWidget_3 = QtWidgets.QTreeWidget(self.tab_3)
        self.treeWidget_3.setGeometry(QtCore.QRect(30, 50, 271, 471))
        self.treeWidget_3.setDragEnabled(True)
        self.treeWidget_3.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.treeWidget_3.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.treeWidget_3.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeWidget_3.setAutoExpandDelay(0)
        self.treeWidget_3.setIndentation(5)
        self.treeWidget_3.setUniformRowHeights(False)
        self.treeWidget_3.setColumnCount(1)
        self.treeWidget_3.setObjectName("treeWidget_3")
        self.treeWidget_3.header().setVisible(False)
        self.treeWidget_3.header().setCascadingSectionResizes(False)
        self.treeWidget_3.header().setDefaultSectionSize(100)
        self.treeWidget_3.header().setHighlightSections(True)
        self.treeWidget_3.header().setMinimumSectionSize(100)
        self.treeWidget_3.header().setSortIndicatorShown(False)
        self.treeWidget_3.header().setStretchLastSection(True)
        self.listWidget_3 = QtWidgets.QListWidget(self.tab_3)
        self.listWidget_3.setGeometry(QtCore.QRect(420, 50, 221, 471))
        self.listWidget_3.setAutoScroll(True)
        self.listWidget_3.setDragEnabled(True)
        self.listWidget_3.setDragDropOverwriteMode(True)
        self.listWidget_3.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.listWidget_3.setDefaultDropAction(QtCore.Qt.TargetMoveAction)
        self.listWidget_3.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listWidget_3.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget_3.setUniformItemSizes(False)
        self.listWidget_3.setObjectName("listWidget_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 859, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Сделать Авто"))
        self.checkBox.setText(_translate("MainWindow", "Монопольно?"))
        self.pushButton_2.setText(_translate("MainWindow", ">>"))
        self.pushButton_5.setText(_translate("MainWindow", "<<"))
        self.label.setText(_translate("MainWindow", "Выбранные магазины :"))
        self.label_6.setText(_translate("MainWindow", "Все магазины :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Главная -> Локальная"))
        self.checkBox_6.setText(_translate("MainWindow", "Монопольно?"))
        self.pushButton_22.setText(_translate("MainWindow", "Сделать Авто"))
        self.label_3.setText(_translate("MainWindow", "Выбранные магазины :"))
        self.pushButton_9.setText(_translate("MainWindow", ">>"))
        self.pushButton_11.setText(_translate("MainWindow", "<<"))
        self.label_7.setText(_translate("MainWindow", "Все магазины :"))
        self.treeWidget_6.headerItem().setText(0, _translate("MainWindow", "Text"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Локальная -> Главная"))
        self.checkBox_3.setText(_translate("MainWindow", "Монопольно?"))
        self.pushButton_13.setText(_translate("MainWindow", "Сделать Авто"))
        self.label_4.setText(_translate("MainWindow", "Выбранные магазины :"))
        self.pushButton_12.setText(_translate("MainWindow", ">>"))
        self.pushButton_14.setText(_translate("MainWindow", "<<"))
        self.label_5.setText(_translate("MainWindow", "Все магазины :"))
        self.treeWidget_3.headerItem().setText(0, _translate("MainWindow", "Text"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Полный круг"))
